### ISSUE TITLE
第1章「Svelteチュートリアル」における画像スライダーのimg要素の配置位置について

### ISSUE THREAD

**Issue by ready-player1** [svelte-book/sample-app#1]
はじめまして、「初版　第1冊」の読者です。Svelte編の内容で恐縮ですが、一点だけ確認させてください。

P.19 App.svelte および P.22 Slider.svelte にて、画像スライダーのimg要素の配置位置は、クラスセレクターで選択したimg要素に対して次のように宣言されています。

- `.slider-imte.left`セレクターの宣言ブロックにて `right: 100%;`と宣言
- `.slider-item.right`セレクターの宣言ブロックにて`left: 100%;`と宣言

こちらはrightプロパティとleftプロパティを入れ替えて次のように宣言しなくてもよろしいでしょうか？

- `.slider-imte.left`セレクターの宣言ブロックにて`left: 100%;`と宣言
- `.slider-item.right`セレクターの宣言ブロックにて`right: 100%;`と宣言

画像スライダーのimg要素が意図した配置となっているか、お手すきの際にご確認願います。

**Comment by notozeki** [comment]
@ready-player1 はじめまして。ご質問ありがとうございます！

`.slider-item.left` と `.slider-item.right` のCSSは、クラス名とCSSプロパティがクロスしていて少し直感と反するのですが、書籍に記載の通りで意図したものとなっています。

例えば `.slider-item.left`  （左のスライダー画像）が `right: 100%` なのは、この画像の**右端** (= `right`) が、中央のスライダー画像の左端と一致するように配置したいためです。`right` にパーセント値を指定すると、その要素の右端が[包含ブロック](https://developer.mozilla.org/ja/docs/Web/CSS/Containing_block)（今回の場合は `.slider`）の右端から包含ブロックの幅の何%分離れているかを指定できます。`100%`  = 包含ブロックの幅 となるため、ぴったり中央の画像の左端の位置と一致します。

`.slider-item.right` についても同様の理由で `left: 100%` を指定しています。

**Comment by ready-player1** [comment]
お忙しい中、ご返信いただきありがとうございます。
そして返信が遅くなり申し訳ありません。

画像スライダーのimg要素が意図した配置となっている旨、承知いたしました。
こちらはクローズさせていただきます。

ご丁寧に説明いただきありがとうございました。
