### ISSUE TITLE
第1章「Svelteチュートリアル」における画像スライダーの左右のボタンを押下した際のハンドラの処理について

### ISSUE THREAD

**Issue by ready-player1** [svelte-book/sample-app#2]
こんばんは。Svelte編の内容で恐縮ですが、一点だけ確認させてください。

P.18 App.svelte の sliderMoveLeft() および sliderMoveRight() における、sliderCenterIndex への代入処理は次のように書かなくてもよろしいでしょうか？

```javascript
// sliderMoveLeft()
sliderCenterIndex = (sliderCenterIndex + 1) % length;
```

```javascript
// sliderMoveRight() 
sliderCenterIndex = (sliderCenterIndex - 1 + length) % length;
```

当該質問をした理由は、左右ボタンを押下した際の画像スライダーの挙動が不自然に感じるためです。具体的には、表示されている矢印の向きと逆方向に画像がスライドするように感じます。感じ方に個人差がある可能性もありますが、念のため確認することにしました。お手すきの際にご確認願います。

※「初版　第1冊」にて確認しました

## 詳細

P.18 App.svelte（コード1.2.10）の冒頭にて、次のような宣言がされています。

```javascript
let sliderCenterIndex = 0;
let sliderLeftIndex = product.images.length - 1;
let sliderRightIndex = 1;
```

ここで宣言されているそれぞれのインデックスを画像の表示位置と対応させて`[sliderLeftIndex, sliderCenterIndex, sliderRightIndex]`の形式で表すと、初期値は

```
[2, 0, 1]
```

となります。この状態において button.slider-left-button（←）を押下した際に、もしインデックスの値が

```
[0, 1, 2]
```

と変化する仕様ならば、冒頭に示した処理で sliderCenterIndex の値を 0 -> 1へ増加させることが適切と考えられます。

## 補足

- P.21, 25, 24 Slider.svelte においても画像スライダーは同様の挙動となっているため、必要であればそちらもあわせてご確認願います
- \#1 にて、画像スライダーのimg要素が意図した配置となっていると回答いただきましたので、今回は表示されている矢印の方向に画像をスライドさせる方法を考えてみました
- 前回の確認テキストを作成した後、別件で忙しくなってしまい、本書を読み進めることができませんでした。今日あらためて頭から読み直しはじめたところです。前回と関連した内容であるにもかかわらず質問の間が空いてしまい失礼しました

**Comment by notozeki** [comment]
@ready-player1 ご質問ありがとうございます！

> 当該質問をした理由は、左右ボタンを押下した際の画像スライダーの挙動が不自然に感じるためです。具体的には、表示されている矢印の向きと逆方向に画像がスライドするように感じます。感じ方に個人差がある可能性もありますが、念のため確認することにしました。お手すきの際にご確認願います。

こちらは、意図通りのものとなっています！スライダーの左右ボタンの考え方には二通りあると考えています。

(1) 画像が移動する方向を指示するもの
(2) 次に見たい画像の方向を指示するもの

サンプルコードでは(2)を想定して作っていたため、このようなコードとなっています。

もちろん(1)を想定して作ってもよく、確かその後のチュートリアルにも特に影響はしなかったはずです。ですので、掲載して頂いたコードで書き換えて進めて頂いても全く問題ありません！

**Comment by ready-player1** [comment]
お忙しい中、ご丁寧に説明いただきありがとうございます。おかげでよく分かりました！

不思議なもので「(2)を想定して作っていたため、このようなコードとなっています」と説明いただいてからは、嘘のように違和感が解消しました。

また、実際にいくつかのショッピングサイトに設置されている画像スライダーの挙動を確認したところ、私が見た範囲では(2)の挙動ばかりでした。勉強になりました。

本件はクローズいたします。回答いただきありがとうございました。
